version: "3.8"
services:
  termifolio:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    ports:
      - "80:8001"
      - "443:8001"
    restart: always
    hostname: huanglipang-termifolio
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 50M
